services:
  # Redis 서비스 추가
  redis:
    image: redis:alpine
    container_name: ai-redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

  ai-service:
    image: golila0611/ai-service:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis_data:
